package spring_security.crypto.encrypt.aes_bytes_encryption;

import org.springframework.security.crypto.encrypt.AesBytesEncryptor;
import org.springframework.security.crypto.keygen.BytesKeyGenerator;
import org.springframework.security.crypto.keygen.KeyGenerators;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * AES_Bytes_Encryption_Demo_V2
 * -------------------------------------------------------------------------
 * This demo illustrates AES encryption and decryption using the
 * following constructor of Spring Security's AesBytesEncryptor:
 * <p>
 * AesBytesEncryptor(String password, CharSequence salt, BytesKeyGenerator ivGenerator)
 * <p>
 * Compared to V1, this version introduces a **custom Initialization Vector (IV)
 * generator**, allowing developers to control how IVs are produced.
 * <p>
 * -------------------------------------------------------------------------
 * ENCRYPTION WORKFLOW
 * -------------------------------------------------------------------------
 * <p>
 * The encryption pipeline executed internally by Spring Security is:
 * <p>
 * User Password
 * │
 * ▼
 * PBKDF2 Key Derivation
 * │
 * ▼
 * AES Secret Key Generation
 * │
 * ▼
 * Initialization Vector (IV)
 * generated by BytesKeyGenerator
 * │
 * ▼
 * AES Encryption (AES/CBC/PKCS5Padding)
 * │
 * ▼
 * Ciphertext
 * <p>
 * -------------------------------------------------------------------------
 * WHAT IS AN INITIALIZATION VECTOR (IV)?
 * -------------------------------------------------------------------------
 * <p>
 * The IV is a random value used during encryption to ensure:
 * <p>
 * • Identical plaintext encrypted multiple times produces
 * different ciphertext.
 * <p>
 * • Protection against pattern analysis attacks.
 * <p>
 * • Improved cryptographic randomness.
 * <p>
 * AES block size = 16 bytes
 * <p>
 * Therefore IV size is typically **16 bytes**.
 * <p>
 * -------------------------------------------------------------------------
 * SECURITY CHARACTERISTICS
 * -------------------------------------------------------------------------
 * <p>
 * • Symmetric AES encryption
 * • Password-based key derivation (PBKDF2)
 * • Random IV generation
 * • Non-deterministic encryption output
 * <p>
 * NOTE:
 * AES encryption is reversible (unlike password hashing).
 */

public class AES_Bytes_Encryption_Demo_V2 {

    private static final Logger logger = Logger.getLogger(AES_Bytes_Encryption_Demo_V2.class.getName());

    public static void main(String[] args) {

        logger.info("=========== AES ENCRYPTION DEMO V2 STARTED ===========");
        try {

            //------------------------------------------------------------------
            // STEP 1: DEFINE PASSWORD AND GENERATE SALT
            //------------------------------------------------------------------
            // The encryption key will not be directly stored.
            // Instead Spring Security derives an AES key using: password + salt
            // via PBKDF2 key derivation.
            // The salt adds randomness and prevents rainbow-table attacks.

            String password = "SecurePassword2026";
            Objects.requireNonNull(password, "Encryption password cannot be null.");
            String salt = KeyGenerators.string().generateKey();
            logger.info("Password defined successfully.");
            logger.info("Generated Salt: " + salt);

            //------------------------------------------------------------------
            // STEP 2: CREATE CUSTOM IV GENERATOR
            //------------------------------------------------------------------
            // A BytesKeyGenerator produces cryptographically secure
            // random bytes used as an Initialization Vector (IV).
            // AES requires a 16-byte IV because AES block size = 128 bits.
            // KeyGenerators.secureRandom(16)
            // creates a generator that produces 16-byte random values.

            BytesKeyGenerator ivGenerator = KeyGenerators.secureRandom(16);
            logger.info("IV Generator initialized (16 bytes).");

            //------------------------------------------------------------------
            // STEP 3: INITIALIZE AES BYTES ENCRYPTOR
            //------------------------------------------------------------------
            // Constructor used in this demo: AesBytesEncryptor(password, salt, ivGenerator)
            // Internally performs:
            // 1) PBKDF2 key derivation
            // 2) AES cipher initialization
            // 3) IV generation through provided generator

            AesBytesEncryptor encryptor = new AesBytesEncryptor(password, salt, ivGenerator);
            logger.info("AES encryptor successfully initialized.");

            //------------------------------------------------------------------
            // STEP 4: PREPARE PLAINTEXT DATA
            //------------------------------------------------------------------
            // Convert plaintext string to UTF-8 encoded bytes.

            String data = "AES Encryption with Custom IV Generator";
            Objects.requireNonNull(data, "Input data cannot be null.");
            byte[] plaintext = data.getBytes(StandardCharsets.UTF_8);
            logger.info("Plaintext prepared for encryption.");
            logger.info("Plaintext length: " + plaintext.length + " bytes");

            //------------------------------------------------------------------
            // STEP 5: PERFORM ENCRYPTION
            //------------------------------------------------------------------
            // encrypt(byte[])
            // Steps internally:
            // plaintext
            //      │
            //      ▼
            // AES encryption with generated IV
            //      │
            //      ▼
            // ciphertext

            byte[] encrypted = encryptor.encrypt(plaintext);
            logger.info("Encryption completed successfully.");

            //------------------------------------------------------------------
            // STEP 6: ENCODE CIPHERTEXT FOR DISPLAY
            //------------------------------------------------------------------
            // Binary ciphertext is not readable.
            // Base64 encoding converts it to a printable string.

            String encodedCiphertext = Base64.getEncoder().encodeToString(encrypted);
            logger.info("Encrypted Data (Base64): " + encodedCiphertext);
            logger.info("Ciphertext length: " + encrypted.length + " bytes");

            //------------------------------------------------------------------
            // STEP 7: PERFORM DECRYPTION
            //------------------------------------------------------------------
            // decrypt(byte[])
            // Reverse process:
            // ciphertext
            //      │
            // AES decryption
            //      │
            // original plaintext

            byte[] decrypted = encryptor.decrypt(encrypted);
            String decryptedText = new String(decrypted, StandardCharsets.UTF_8);
            logger.info("Decryption completed successfully.");
            logger.info("Decrypted text: " + decryptedText);

            //------------------------------------------------------------------
            // STEP 8: INTEGRITY VERIFICATION
            //------------------------------------------------------------------
            // Verify decrypted text equals original plaintext.

            boolean integrityCheck = data.equals(decryptedText);
            if (integrityCheck) {
                logger.info("Integrity verification: SUCCESS");
            } else {
                logger.warning("Integrity verification: FAILED");
            }
            logger.info("=========== AES ENCRYPTION DEMO V2 COMPLETED ===========");
        }
        //------------------------------------------------------------------
        // EXCEPTION HANDLING
        //------------------------------------------------------------------

        catch (IllegalArgumentException ex) {
            logger.log(Level.SEVERE, "Invalid argument supplied to encryption process.", ex);

        } catch (IllegalStateException ex) {
            logger.log(Level.SEVERE, "Encryption/Decryption operation failed. "
                    + "Possible causes include incorrect password, "
                    + "invalid salt, or corrupted ciphertext.", ex);
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Unexpected system error occurred.", ex);
        }
    }
}
